{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultError"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dvesecurity\/keychainerror\/resulterror"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DVESecurity\/documentation\/DVESecurity\/KeychainError\/resultError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A keychain query returned an unexpected or unknown result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultError"}],"title":"KeychainError.resultError","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:11DVESecurity13KeychainErrorO06resultC0yA2CmF","modules":[{"name":"DVESecurity"}]},"hierarchy":{"paths":[["doc:\/\/DVESecurity\/documentation\/DVESecurity","doc:\/\/DVESecurity\/documentation\/DVESecurity\/KeychainError"]]},"references":{"doc://DVESecurity/documentation/DVESecurity":{"role":"collection","title":"DVESecurity","abstract":[{"type":"text","text":"Secure your app data with cryptographic functions and by using keychains."}],"identifier":"doc:\/\/DVESecurity\/documentation\/DVESecurity","kind":"symbol","type":"topic","url":"\/documentation\/dvesecurity"},"doc://DVESecurity/documentation/DVESecurity/KeychainError":{"role":"symbol","title":"KeychainError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainError"}],"abstract":[{"type":"text","text":"The type for errors thrown by Keychain methods."}],"identifier":"doc:\/\/DVESecurity\/documentation\/DVESecurity\/KeychainError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainError"}],"url":"\/documentation\/dvesecurity\/keychainerror"},"doc://DVESecurity/documentation/DVESecurity/KeychainError/resultError":{"role":"symbol","title":"KeychainError.resultError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resultError"}],"abstract":[{"type":"text","text":"A keychain query returned an unexpected or unknown result."}],"identifier":"doc:\/\/DVESecurity\/documentation\/DVESecurity\/KeychainError\/resultError","kind":"symbol","type":"topic","url":"\/documentation\/dvesecurity\/keychainerror\/resulterror"}}}